version: "3.9"

services:
  api:
    build: .
    container_name: nestjs-app
    ports:
      - "3000:3000"
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/mydb
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
